<?php

$pdf = new Pdf('P', 'inchi', 'Letter', true, 'UTF-8', false);
$pdf->SetTitle('SSP');
$pdf->SetHeaderMargin(20);
$pdf->SetTopMargin(20);
$pdf->setFooterMargin(20);
$pdf->SetAutoPageBreak(true);
$pdf->SetAuthor('Toyyibe');
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
// $pdf->SetDisplayMode('real', 'default');

// set font
$pdf->SetFont('Times', '', 10);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

$html = '
<table class="table table-condensed" border="1">
	<tr>
		<td class="col-xs-2">
			KEMENTRIAN KEUANGAN R.I<BR/>
			DIREKTORAT JENDRAL PAJAK
		</td>
		<td class="col-xs-5">
		
		</td>
		<td class="col-xs-5">
		
		</td>
	</tr>
</table>
';

$pdf->startPage();

$pdf->AddPage();

$html2 = '

<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel"s Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="BLANKO-SSP_5679" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=804 class=xl725679
 style="border-collapse:collapse;table-layout:fixed;width:602pt">
 <col class=xl725679 width=23 style="mso-width-source:userset;mso-width-alt:
 841;width:17pt">
 <col class=xl725679 width=19 style="mso-width-source:userset;mso-width-alt:
 694;width:14pt">
 <col class=xl725679 width=24 span=30 style="mso-width-source:userset;
 mso-width-alt:877;width:18pt">
 <col class=xl725679 width=19 style="mso-width-source:userset;mso-width-alt:
 694;width:14pt">
 <col class=xl725679 width=23 style="width:17pt">
 <tr height=18 style="height:13.5pt">
  <td height=18 class=xl725679 width=23 style="height:13.5pt;width:17pt"></td>
  <td class=xl725679 width=19 style="width:14pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=24 style="width:18pt"></td>
  <td class=xl725679 width=19 style="width:14pt"></td>
  <td class=xl725679 width=23 style="width:17pt"></td>
 </tr>
 <tr height=15 style="mso-height-source:userset;height:11.25pt">
  <td height=15 class=xl725679 style="height:11.25pt"></td>
  <td class=xl735679><a name="RANGE!B2:AG67">&nbsp;</a></td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td colspan=9 class=xl1725679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td colspan=10 rowspan=2 class=xl1965679 style="border-right:1.0pt solid black">SURAT
  SETORAN PAJAK</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl755679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=21 style="mso-height-source:userset;height:15.75pt">
  <td height=21 class=xl725679 style="height:15.75pt"></td>
  <td align=left valign=top><!--[if gte vml 1]><v:shapetype id="_x0000_t75"
   coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe"
   filled="f" stroked="f">
   <v:stroke joinstyle="miter"/>
   <v:formulas>
    <v:f eqn="if lineDrawn pixelLineWidth 0"/>
    <v:f eqn="sum @0 1 0"/>
    <v:f eqn="sum 0 0 @1"/>
    <v:f eqn="prod @2 1 2"/>
    <v:f eqn="prod @3 21600 pixelWidth"/>
    <v:f eqn="prod @3 21600 pixelHeight"/>
    <v:f eqn="sum @0 0 1"/>
    <v:f eqn="prod @6 1 2"/>
    <v:f eqn="prod @7 21600 pixelWidth"/>
    <v:f eqn="sum @8 21600 0"/>
    <v:f eqn="prod @7 21600 pixelHeight"/>
    <v:f eqn="sum @10 21600 0"/>
   </v:formulas>
   <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
   <o:lock v:ext="edit" aspectratio="t"/>
  </v:shapetype><v:shape id="Picture_x0020_1" o:spid="_x0000_s14341" type="#_x0000_t75"
   alt="image002" style="position:absolute;margin-left:4.5pt;margin-top:3.75pt;
   width:59.25pt;height:56.25pt;z-index:1;visibility:visible" o:gfxdata="UEsDBBQABgAIAAAAIQBamK3CDAEAABgCAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRwU7DMAyG
70i8Q5QralM4IITW7kDhCBMaDxAlbhvROFGcle3tSdZNgokh7Rjb3+8vyWK5tSObIJBxWPPbsuIM
UDltsK/5x/qleOCMokQtR4dQ8x0QXzbXV4v1zgOxRCPVfIjRPwpBagArqXQeMHU6F6yM6Rh64aX6
lD2Iu6q6F8phBIxFzBm8WbTQyc0Y2fM2lWcTjz1nT/NcXlVzYzOf6+JPIsBIJ4j0fjRKxnQ3MaE+
8SoOTmUi9zM0GE83SfzMhtz57fRzwYF7S48ZjAa2kiG+SpvMhQ4kvFFxEyBNlf/nZFFLhes6o6Bs
A61m8ih2boF2XxhgujS9Tdg7TMd0sf/X5hsAAP//AwBQSwMEFAAGAAgAAAAhAAjDGKTUAAAAkwEA
AAsAAABfcmVscy8ucmVsc6SQwWrDMAyG74O+g9F9cdrDGKNOb4NeSwu7GltJzGLLSG7avv1M2WAZ
ve2oX+j7xL/dXeOkZmQJlAysmxYUJkc+pMHA6fj+/ApKik3eTpTQwA0Fdt3qaXvAyZZ6JGPIoiol
iYGxlPymtbgRo5WGMqa66YmjLXXkQWfrPu2AetO2L5p/M6BbMNXeG+C934A63nI1/2HH4JiE+tI4
ipr6PrhHVO3pkg44V4rlAYsBz3IPGeemPgf6sXf9T28OrpwZP6phof7Oq/nHrhdVdl8AAAD//wMA
UEsDBBQABgAIAAAAIQBbxStFLwIAALMFAAASAAAAZHJzL3BpY3R1cmV4bWwueG1srFTbjtMwEH1H
4h8sv7O5Nck2arKqtlqEtECF4ANcZ9JYJHZku5f9e8ZxmtIHJER5G8+MzzlzsVdP574jR9BGKFnS
6CGkBCRXtZD7kv74/vLhkRJjmaxZpySU9A0Mfarev1uda10wyVulCUJIU6CjpK21QxEEhrfQM/Og
BpAYbZTumcWj3ge1ZicE77sgDsMsMIMGVpsWwG58hFYjtj2pZ+i6taeAWti1KSlqcN4pp9Gq99lc
dVW0CpwoZ44IaHxtmirLsjydQ84zRrU6VbF3O/Pic/E0j9JwDo03RuQrnVUzRbWYsWefuxJl0TL+
A282g9/wLtPLBVR0pb2QDYL7dHncCr7VE92X41YTUePwFkmSUyJZj3PCDHvQQCJKajAcRyN6tocw
jGlwvehhWIHQr4r/NNMo2T8MsmdCIrl6bpncw9oMwC1q+s2lsarWDdu5UYSfFsr3KsbjTWm7Tgwv
osNxssLZd6vzi/pXa6qaRnDYKH7oQVq/qxo6ZvGdmFYMhhJdQL8DbLz+VI8FscJo/g3rvlcoNgex
rAbL23uxHFSDTXS6XNNn4GkA1ya7x2MGXKbd6bOqcYfYwSp8aaw4N7r/HzqwqeRc0vgxzVP8aN5K
muTRIk/dNrACzpZwDOdJsohTSjjGs2WaoO2FOxkucdDGfgR1tyTigHB82JmxTHZ8NVOPLhSOTiq3
hPfW70q4dHgy8dVNT7ETuGQbZtkl6+b3m9L9b1v9AgAA//8DAFBLAwQUAAYACAAAACEAqiYOvrwA
AAAhAQAAHQAAAGRycy9fcmVscy9waWN0dXJleG1sLnhtbC5yZWxzhI9BasMwEEX3hdxBzD6WnUUo
xbI3oeBtSA4wSGNZxBoJSS317SPIJoFAl/M//z2mH//8Kn4pZRdYQde0IIh1MI6tguvle/8JIhdk
g2tgUrBRhnHYffRnWrHUUV5czKJSOCtYSolfUma9kMfchEhcmzkkj6WeycqI+oaW5KFtjzI9M2B4
YYrJKEiT6UBctljN/7PDPDtNp6B/PHF5o5DOV3cFYrJUFHgyDh9h10S2IIdevjw23AEAAP//AwBQ
SwMEFAAGAAgAAAAhAJ7M2MsaAQAAigEAAA8AAABkcnMvZG93bnJldi54bWxUkFFPgzAUhd9N/A/N
NfHFuAKDoZOyLOqWGRKTTRNfG1oGkbakrYD+eotsIb713Hu/c89tsupFjVquTaUkAX/mAeIyV6yS
RwLvb5vbO0DGUslorSQn8M0NrNLLi4QumerknrcHe0TORJolJVBa2ywxNnnJBTUz1XDpeoXSglon
9REzTTtnLmoceN4CC1pJt6GkDX8sef55+BIE9n6Gb4ps94FfNvb5ybYs224ZIddX/foBkOW9nYZP
9I65+OF8HsNwjntD6jL29VrmpdKo2HNT/bgDxnqhlUBadQQCQLmqh/qgX4vCcEsgjBdB9Nc5V6LY
jzzAg6lVI7o4oeE/1L/33OBgekb92A9HFk+J0sSJ6QvTXwAAAP//AwBQSwMECgAAAAAAAAAhAJ09
MhzRCAAA0QgAABQAAABkcnMvbWVkaWEvaW1hZ2UxLnBuZ4lQTkcNChoKAAAADUlIRFIAAABNAAAA
UAgDAAAAa58IxwAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAAABgUExURQAA
ABERETMzMyIiIkRERFVVVWZmZnd3d4iIiJmZmaqqqru7u8zMzN3d3e7u7v///wECAwECAwECAwEC
AwECAwECAwECAwECAwECAwECAwECAwECAwECAwECAwECAwECA4u1i2gAAAAMY21QUEpDbXAwNzEy
AAAAA0gAc7wAAAfvSURBVFhH7ZjZdsM2DEQlLgB3/v/f9oKS7ChxEjenj2U2x5KGWAYD0Nv8L9f2
Hlh677a30EZIcbyD9w5alT661Dfg3kBLaeYtz6S/w/2KNmIbYdu2MNrv3v6GlmVUv21u23wbkn8x
7xc0TbNs215m2bc3vP0RrYc2BcM6JnXMk1mjvf52/YRWQm94Gc6HiZ5vPZS/oeFlxstnrPLyVtP3
1PvWNnI59fTyssa81flDbr9DK3GYl/LJLaLoe4/fefsNmqSZ8PIr/yveck1ee/sSrbk6cMq9emQY
+2Yl2y/WKzRqiIDv31WSHsl4xeSvaERlEJ795ebLngZcnOUF9b6gFZ0dZ46avMyr7h73yG596pdk
fEZL1cLva7Vs9v2I3PDdHVHqYiZLtdrNs34W0Ttaw3ooH8YInqdKXwwpMeW0aqCHbkZ7NwbmBVTv
Ho8bWma7xYCZcxw152bEr3GMyePQBaiR5ojcaNSGQenm7Qe0wUbHLbPHGXsPEs2kIBKC/QKGS3ld
xSbz1nTgA4+eaETKKscuFlIG36VhhM6QizotGTSpI4xZZEZECnCrvGX0uR5o8KcisctwoRSyjpyc
4FOIMSo/aEl0nkhyaxLMZFvigrePZJxoA27jpV9BzbUkcyeUprwTnYAlDorBGJJLqlKpi71GPXTg
KrQDreiwijlrnJRGSDdTz7GGKVETX1FmDpKwCaoRj1P2lg7AmYWz0KCheXkaXHiAbz9rUeXpQuAK
YSs9S2uAmHl8n9k81CGvh0GzXCKL/gxmwfSpffqW1CflHyS4IbpjupZpNH2f3W6BvmuZcqXDW9As
LU+9nsEaZ4UYJaUUvY7qVPhybTgX0ZWMuexsZh/LOmTk9zA0PwF7ChbksAqaor0UldC7z7XWsvdU
ciNACkHoNWTpwQwSGOxf0LTS5K5WVImalYtpBCzRmPvcW2+97hZAm0fgF/tV5cXFtA61eMPQigxj
zbHcbjZb4KoMVb9jtCNqjbovTgruSOmEnBdxt2JenMAcBcJy6qfD77WqWkalz5L7NqPkzWwQVYWu
9NVMvW8jFwsFWUVx1orIsSEbmjTd9hMt2aakDMaFmlpIlFFaaGl4p2SghoG7bMgtZo+tfdNmZDU0
aHQFDrabn/bN0CbRE7qZIimNifGGvEyNjzsuNMLWxOi32OsN/PQUcGaPxOYYFBKcgBLUWkwSorMC
1EbfoFTzHKf6mmsrhAstdNnWf2WJJHLjZtOqPStCNJKSBOg1YId967pukfZhueo3OcR5oWWlsEym
Slh/MKes6RQsMki1thbVISP7GJLCKCgLN/YtrHqAH1h6oQ2Hq+Z3zkupqRIyuAvhhyL01lTV1SCZ
Kq1xdxS9cXLEbiJMWe7z6L2Hhjh6njEbGRpWzbGilDWVmMuOSjqS6lvEQE9Ia6Qi8JPhYhUF/IjY
80SjZhZH1ptHobvYKfniMpxi0GqejlKMFKlH19Fhu+0wad8yaXui4d8qh7JUicDg2T4U1cUqmJdS
dtSVvXY6d6d1xHWnxcdiDv2eaMTdG0eajxaQ7noMNUQtkNe7KXRASS6DAd3sSnfc1uAjf4wPZ7s9
lVxOjjhKhqzTrtwMmGA1oFVcQM0rfSIPdRbH0KkJDDIUBz9O1T7RiO0qh5UjcYTK/CoZmKg1atZg
WVJEWFKCldUZgN1OHZGv5eiZU1Og3WKGvxbXRNQsOrSW7L0UQIuUTJKo6XXNojbUOI9sm0Ld0HDM
dERrDrHS0bfu6pYl1RB4T/hKDkXiyLBV143jNYZsmhbh1hm2h22p2R5GOIuc0J1QLJKhzrnUtrA1
IlcEYmnfmAG4x/SXH8abdjXUqzv3UzKzVQxFuNOUXUNsUTdmJOE1fzSH5qncfU0zw+rqAz+ecUOE
qF3u2IIEleyir4hWjLbxcNWNzNsxIoXVi8+i3GcOC7R/NIjH5BBPjlDQ2MbTxQ9aFt2IatuVUsjW
iCOiWUA325DgJZQWnnsWqL+z1+AM81WJshOV7oLgFtYUOkZAy3vcCSAzGGEwb00/HlPXwzY2OLu9
bkweqlyJSGLWIuI3L1LgH2EkOnDaxUNfTSifA/Bz4qIh0itsu/OUBp9WVaO7qES0jgzh4ON5fWmQ
PfPsq0+01NLZaxDJYsrNRANar3WddiuxAi1UJhsq4mjnA/1A2L/EbdI/bTJey07eNixDzd3TY1JN
aLrfIbgp23mdF1cj/ZwF61XU7/l2ihmtIGNCtwKIQYTBSwQRbIFrF13FHH2Oqh/mXsHVq3kjmd0U
R2piwImVubBlKJFgHO324Rt1/eTHB/aaIDzaKvGAENRmysKZRYpkTYkBNLciYXf+NIdGerSGL55a
7146YotyZsBnoCy1oEYRKzXTvRKwGHv1eMvb65ncOry7jt1975RXyTnYuMDAVRGS4AOUYxeuHpve
+XHzlLlo6chaJeKTC+V+qKREmJPa47Rr+vHxqPjxLNMQm2PEt4pxdiT4ukYhpOceix8fP4S4nYws
cNdWP3ySki8eMVLO21n9hkaLf3LklWGf3kPD7LD0MqcEK2P7Wx+NndHYcr4d/W+2Dbl05A3DrDfj
6G3zGxpy8+DIG3jGj5ujjy5z8qKiV53P7n77Wjegh8dp67HutvEJIOLz/uJTwx/Q7EjhvfNv/Tgf
Pjn6yVM7X/2bZeet7z3lREY3fn9d9Xoh3uNGRfH19/UZ7e9I9uT/aH+L338bt38AJzIW4aJANzEA
AAAASUVORK5CYIJQSwECLQAUAAYACAAAACEAWpitwgwBAAAYAgAAEwAAAAAAAAAAAAAAAAAAAAAA
W0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAAIQAIwxik1AAAAJMBAAALAAAAAAAAAAAA
AAAAAD0BAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAAIQBbxStFLwIAALMFAAASAAAAAAAAAAAA
AAAAADoCAABkcnMvcGljdHVyZXhtbC54bWxQSwECLQAUAAYACAAAACEAqiYOvrwAAAAhAQAAHQAA
AAAAAAAAAAAAAACZBAAAZHJzL19yZWxzL3BpY3R1cmV4bWwueG1sLnJlbHNQSwECLQAUAAYACAAA
ACEAnszYyxoBAACKAQAADwAAAAAAAAAAAAAAAACQBQAAZHJzL2Rvd25yZXYueG1sUEsBAi0ACgAA
AAAAAAAhAJ09MhzRCAAA0QgAABQAAAAAAAAAAAAAAAAA1wYAAGRycy9tZWRpYS9pbWFnZTEucG5n
UEsFBgAAAAAGAAYAhAEAANoPAAAAAA==
">
   <v:imagedata src="BLANKO-SSPss_files/BLANKO-SSP_5679_image001.png" o:title=""/>
   <x:ClientData ObjectType="Pict">
    <x:SizeWithCells/>
    <x:CF>Bitmap</x:CF>
    <x:AutoPict/>
   </x:ClientData>
  </v:shape><![endif]--><![if !vml]><span style="mso-ignore:vglayout;
  position:absolute;z-index:1;margin-left:6px;margin-top:5px;width:79px;
  height:75px">
  <!--imgx-->
  </span><![endif]><span
  style="mso-ignore:vglayout2">
  <table cellpadding=0 cellspacing=0>
   <tr>
    <td height=21 class=xl765679 width=19 style="height:15.75pt;width:14pt">&nbsp;</td>
   </tr>
  </table>
  </span></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl655355679></td>
  <td class=xl1035679></td>
  <td class=xl785679></td>
  <td class=xl785679></td>
  <td class=xl785679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td colspan=2 rowspan=2 class=xl1625679 style="border-right:1.0pt solid black;
  border-bottom:1.0pt solid black">1</td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="mso-height-source:userset;height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td colspan=10 class=xl1735679 style="border-right:1.0pt solid black">DEPARTEMEN
  KEUANGAN R.I.</td>
  <td colspan=10 rowspan=3 class=xl2025679 style="border-right:1.0pt solid black">(SSP)</td>
  <td class=xl725679></td>
  <td class=xl1015679 colspan=3>LEMBAR</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td colspan=10 class=xl1755679 style="border-right:1.0pt solid black">DIREKTORAT
  JENDERAL PAJAK</td>
  <td class=xl1055679></td>
  <td class=xl1165679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td colspan=9 class=xl1955679><a name="RANGE!E6"></a></td>
  <td class=xl1045679></td>
  <td class=xl725679></td>
  <td class=xl1165679 colspan=7>Untuk Arsip Wajib Pajak</td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=9 style="mso-height-source:userset;height:6.75pt">
  <td height=9 class=xl725679 style="height:6.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="mso-height-source:userset;height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td class=xl735679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl755679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=5 style="mso-height-source:userset;height:3.75pt">
  <td height=5 class=xl725679 style="height:3.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=5 rowspan=2 class=xl1555679>NPWP</td>
  <td rowspan=2 class=xl715679>:</td>
  <td rowspan=2 class=xl1705679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1705679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1775679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1705679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1775679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1795679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1705679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1775679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1705679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1775679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=9 style="mso-height-source:userset;height:6.95pt">
  <td height=9 class=xl725679 style="height:6.95pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=28 class=xl695679>Diisi sesuai dengan Nomor Pokok Wajib
  Pajak<span style="mso-spacerun:yes">  </span>yang dimiliki</td>
  <td class=xl695679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=5 rowspan=2 class=xl1555679>NAMA WP</td>
  <td rowspan=2 class=xl715679>:</td>
  <td colspan=24 rowspan=2 class=xl1455679>………….……………………...……………………………………….…………………………………………………………………………………………….</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=8 style="mso-height-source:userset;height:6.0pt">
  <td height=8 class=xl725679 style="height:6.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl725679 style="height:7.7pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl1055679><a name="RANGE!I14:AD15"></a></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr class=xl835679 height=20 style="height:15.0pt">
  <td height=20 class=xl835679 style="height:15.0pt"></td>
  <td class=xl825679>&nbsp;</td>
  <td colspan=5 class=xl705679>ALAMAT WP</td>
  <td class=xl715679>:</td>
  <td colspan=24 class=xl1455679>………….……………………...……………………………………….…………………………………………………………………………………………….</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl835679></td>
 </tr>
 <tr height=24 style="mso-height-source:userset;height:18.0pt">
  <td height=24 class=xl725679 style="height:18.0pt"></td>
  <td class=xl795679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td colspan=24 class=xl1135679>………….……………………...……………………………………….…………………………………………………………………………………………….</td>
  <td class=xl1155679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:8.1pt">
  <td height=10 class=xl725679 style="height:8.1pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=5 style="mso-height-source:userset;height:3.75pt">
  <td height=5 class=xl725679 style="height:3.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=5 rowspan=2 class=xl1555679>NOP</td>
  <td rowspan=2 class=xl715679>:</td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1705679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1775679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1795679 style="border-bottom:.5pt solid black">&nbsp;</td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=9 style="mso-height-source:userset;height:6.95pt">
  <td height=9 class=xl725679 style="height:6.95pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1315679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1315679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1335679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1335679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1335679>&nbsp;</td>
  <td class=xl815679></td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1345679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=28 class=xl695679>Diisi sesuai dengan Nomor Objek Pajak</td>
  <td class=xl695679></td>
  <td class=xl695679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=8 style="mso-height-source:userset;height:6.0pt">
  <td height=8 class=xl725679 style="height:6.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=5 class=xl705679>ALAMAT OP</td>
  <td class=xl725679>:</td>
  <td colspan=24 class=xl1455679>………….……………………...……………………………………….…………………………………………………………………………………………….</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr class=xl835679 height=26 style="mso-height-source:userset;height:20.1pt">
  <td height=26 class=xl835679 style="height:20.1pt"></td>
  <td class=xl1225679>&nbsp;</td>
  <td class=xl1235679>&nbsp;</td>
  <td class=xl1235679>&nbsp;</td>
  <td class=xl1235679>&nbsp;</td>
  <td class=xl1235679>&nbsp;</td>
  <td class=xl1235679>&nbsp;</td>
  <td class=xl1235679>&nbsp;</td>
  <td colspan=24 class=xl1515679>………….……………………...……………………………………….…………………………………………………………………………………………….</td>
  <td class=xl1405679>&nbsp;</td>
  <td class=xl835679></td>
 </tr>
 <tr height=17 style="mso-height-source:userset;height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=6 rowspan=2 class=xl1665679>Uraian Pembayaran :<font
  class="font55679"><span style="mso-spacerun:yes"> </span></font></td>
  <td colspan=10 rowspan=2 class=xl1675679>……………………………………………...……………………………….</td>
  <td class=xl1375679 style="border-top:none">&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl725679 style="height:7.7pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=6 rowspan=2 class=xl1005679>Kode Akun Pajak</td>
  <td class=xl725679></td>
  <td colspan=5 rowspan=2 class=xl1005679>Kode Jenis Setoran</td>
  <td class=xl725679></td>
  <td class=xl845679><span style="mso-spacerun:yes"> </span></td>
  <td class=xl1385679>&nbsp;</td>
  <td class=xl665679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.5pt">
  <td height=10 class=xl725679 style="height:7.5pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl845679>&nbsp;</td>
  <td colspan=16 rowspan=2 class=xl1455679>……………………………………………...…………………..…………………………………………………….</td>
  <td class=xl1385679>&nbsp;</td>
  <td class=xl665679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.5pt">
  <td height=10 class=xl725679 style="height:7.5pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1205679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=5 style="mso-height-source:userset;height:3.75pt">
  <td height=5 class=xl725679 style="height:3.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl855679></td>
  <td class=xl1365679>&nbsp;</td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=16 rowspan=2 class=xl1455679>……………………………………………...…………………..……………………………………………………</td>
  <td class=xl1205679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=9 style="mso-height-source:userset;height:6.95pt">
  <td height=9 class=xl725679 style="height:6.95pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1345679>&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1345679 style="border-left:none">&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1335679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1205679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=16 rowspan=2 class=xl1465679 style="border-bottom:1.0pt solid black">……………………………………………...…………………..……………………………………………………</td>
  <td class=xl1205679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl725679 style="height:7.7pt"></td>
  <td class=xl865679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl795679>&nbsp;</td>
  <td class=xl805679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr class=xl885679 height=25 style="mso-height-source:userset;height:18.95pt">
  <td height=25 class=xl885679 style="height:18.95pt"></td>
  <td colspan=24 class=xl1815679 style="border-right:.5pt solid black">Masa
  Pajak</td>
  <td class=xl885679></td>
  <td class=xl885679></td>
  <td colspan=4 rowspan=2 class=xl1005679>Tahun Pajak</td>
  <td class=xl885679></td>
  <td class=xl895679>&nbsp;</td>
  <td class=xl885679></td>
 </tr>
 <tr class=xl885679 height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl885679 style="height:7.7pt"></td>
  <td colspan=2 rowspan=2 class=xl1615679>Jan</td>
  <td colspan=2 rowspan=2 class=xl1505679>Feb</td>
  <td colspan=2 rowspan=2 class=xl1505679>Mar</td>
  <td colspan=2 rowspan=2 class=xl1505679>Apr</td>
  <td colspan=2 rowspan=2 class=xl1505679>Mei</td>
  <td colspan=2 rowspan=2 class=xl1505679>Jun</td>
  <td colspan=2 rowspan=2 class=xl1505679>Jul</td>
  <td colspan=2 rowspan=2 class=xl1505679>Ags</td>
  <td colspan=2 rowspan=2 class=xl1505679>Sep</td>
  <td colspan=2 rowspan=2 class=xl1505679>Okt</td>
  <td colspan=2 rowspan=2 class=xl1505679>Nov</td>
  <td colspan=2 rowspan=2 class=xl1505679>Des</td>
  <td class=xl885679></td>
  <td class=xl885679></td>
  <td class=xl885679></td>
  <td class=xl895679>&nbsp;</td>
  <td class=xl885679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl725679 style="height:7.7pt"></td>
  <td class=xl885679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=6 style="mso-height-source:userset;height:4.5pt">
  <td height=6 class=xl725679 style="height:4.5pt"></td>
  <td colspan=2 rowspan=2 class=xl1865679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl2085679 style="border-right:.5pt solid black;
  border-bottom:.5pt solid black">&nbsp;</td>
  <td colspan=2 rowspan=2 class=xl1495679>&nbsp;</td>
  <td class=xl885679></td>
  <td class=xl725679></td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr class=xl905679 height=12 style="mso-height-source:userset;height:9.0pt">
  <td height=12 class=xl905679 style="height:9.0pt"></td>
  <td class=xl885679></td>
  <td class=xl725679></td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1325679>&nbsp;</td>
  <td class=xl1345679>&nbsp;</td>
  <td class=xl1355679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl905679></td>
 </tr>
 <tr height=20 style="mso-height-source:userset;height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td colspan=24 class=xl1575679 style="border-right:.5pt solid black">Beri
  tanda silang (x) pada kolom bulan, sesuai dengan pembayaran untuk masa yang
  berkenaan</td>
  <td colspan=8 class=xl1525679 style="border-right:1.0pt solid black;
  border-left:none">Diisi Tahun terutangnya Pajak</td>
  <td class=xl725679></td>
 </tr>
 <tr height=13 style="mso-height-source:userset;height:9.95pt">
  <td height=13 class=xl725679 style="height:9.95pt"></td>
  <td class=xl1215679>&nbsp;</td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl1445679 style="border-top:none">&nbsp;</td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl1445679 style="border-top:none">&nbsp;</td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl1445679 style="border-top:none">&nbsp;</td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl915679></td>
  <td class=xl1445679 style="border-top:none">&nbsp;</td>
  <td class=xl925679></td>
  <td class=xl935679></td>
  <td class=xl935679></td>
  <td class=xl935679></td>
  <td class=xl935679></td>
  <td class=xl935679></td>
  <td class=xl935679></td>
  <td class=xl945679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=5 style="mso-height-source:userset;height:3.75pt">
  <td height=5 class=xl725679 style="height:3.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td colspan=5 rowspan=2 class=xl1555679>Nomor Ketetapan</td>
  <td class=xl725679></td>
  <td rowspan=2 class=xl1605679>:</td>
  <td class=xl1305679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td rowspan=2 class=xl1485679>/</td>
  <td class=xl1305679 style="border-left:none">&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td rowspan=2 class=xl1485679>/</td>
  <td class=xl1305679 style="border-left:none">&nbsp;</td>
  <td class=xl1065679>&nbsp;</td>
  <td rowspan=2 class=xl1485679>/</td>
  <td class=xl1305679 style="border-left:none">&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1065679>&nbsp;</td>
  <td rowspan=2 class=xl1485679>/</td>
  <td class=xl1305679 style="border-left:none">&nbsp;</td>
  <td class=xl1065679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl725679 style="height:7.7pt"></td>
  <td class=xl1425679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679 style="border-left:none">&nbsp;</td>
  <td class=xl1325679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1335679>&nbsp;</td>
  <td class=xl1315679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1325679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl1335679>&nbsp;</td>
  <td class=xl1315679 style="border-left:none">&nbsp;</td>
  <td class=xl1075679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=21 style="mso-height-source:userset;height:15.95pt">
  <td height=21 class=xl725679 style="height:15.95pt"></td>
  <td class=xl1435679>&nbsp;</td>
  <td class=xl1105679 colspan=11>Diisi sesuai Nomor Ketetapan : STP, SKPKB,
  SKPKBT</td>
  <td class=xl1105679></td>
  <td class=xl1105679></td>
  <td class=xl1105679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl815679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=10 style="mso-height-source:userset;height:7.7pt">
  <td height=10 class=xl725679 style="height:7.7pt"></td>
  <td colspan=14 class=xl1845679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1245679>&nbsp;</td>
  <td class=xl1255679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=9 style="mso-height-source:userset;height:6.75pt">
  <td height=9 class=xl725679 style="height:6.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=22 style="mso-height-source:userset;height:17.1pt">
  <td height=22 class=xl725679 style="height:17.1pt"></td>
  <td class=xl685679>&nbsp;</td>
  <td class=xl705679 colspan=6>Jumlah Pembayaran</td>
  <td class=xl1005679>:</td>
  <td colspan=17 class=xl1455679>…………………………………………………………………………….…………………………………….</td>
  <td colspan=6 class=xl1565679>Diisi dengan rupiah penuh</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=22 style="mso-height-source:userset;height:16.5pt">
  <td height=22 class=xl725679 style="height:16.5pt"></td>
  <td class=xl1085679>&nbsp;</td>
  <td class=xl705679 colspan=3>Terbilang :</td>
  <td colspan=27 class=xl1455679><span
  style="mso-spacerun:yes"> </span>………………………………….……………………………………………...…………………………...……………………………………………………………………</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=22 style="mso-height-source:userset;height:17.1pt">
  <td height=22 class=xl725679 style="height:17.1pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td colspan=30 class=xl1455679>………………………………………………….…….……………...………………………………………………………………………………………………………………………………..</td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=22 style="mso-height-source:userset;height:17.1pt">
  <td height=22 class=xl725679 style="height:17.1pt"></td>
  <td class=xl1095679>&nbsp;</td>
  <td colspan=30 class=xl1455679><a name="RANGE!Q20:AD21"></a><a
  name="RANGE!Q44:AD46"></a><a name="RANGE!C47">………………………………………………….…….……………...………………………………………………………………………………………………………………………………..</a></td>
  <td class=xl1395679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=8 style="mso-height-source:userset;height:6.0pt">
  <td height=8 class=xl725679 style="height:6.0pt"></td>
  <td class=xl955679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl735679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl745679>&nbsp;</td>
  <td class=xl755679 style="border-top:none">&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=21 style="height:15.75pt">
  <td height=21 class=xl725679 style="height:15.75pt"></td>
  <td colspan=16 class=xl2055679>Diterima oleh Kantor Penerima Pembayaran</td>
  <td colspan=16 class=xl2055679 style="border-right:1.0pt solid black">Wajib
  Pajak/Penyetor</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td colspan=3 class=xl1945679>Tanggal<span style="mso-spacerun:yes"> </span></td>
  <td class=xl1115679 colspan=8><a name="RANGE!G50">……………………………………………</a></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl725679></td>
  <td colspan=7 class=xl2065679><a name="RANGE!R50">………………………………..</a></td>
  <td class=xl1005679>,</td>
  <td class=xl1415679 colspan=2><a name="RANGE!Z50">Tanggal<span
  style="display:none"><span style="mso-spacerun:yes"> </span></span></a></td>
  <td class=xl1115679 colspan=5>……………...………….</td>
  <td class=xl1125679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=16 style="mso-height-source:userset;height:12.0pt">
  <td height=16 class=xl725679 style="height:12.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl725679></td>
  <td class=xl1175679 colspan=6>Cap dan tanda tangan</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl725679></td>
  <td colspan=16 class=xl1885679 style="border-right:1.0pt solid black">Cap dan
  tanda tangan</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td class=xl845679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl1195679 colspan=4>Nama Jelas :<span
  style="mso-spacerun:yes"> </span></td>
  <td class=xl1185679 colspan=7><a name="RANGE!H56">…………………………………….</a></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl1055679></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl1195679></td>
  <td class=xl1195679 colspan=4>Nama Jelas :<span
  style="mso-spacerun:yes"> </span></td>
  <td class=xl1185679 colspan=8><a name="RANGE!X56">…………………………………………..</a></td>
  <td class=xl1055679></td>
  <td class=xl1025679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=5 style="mso-height-source:userset;height:3.75pt">
  <td height=5 class=xl725679 style="height:3.75pt"></td>
  <td class=xl1265679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1145679>&nbsp;</td>
  <td class=xl1145679>&nbsp;</td>
  <td class=xl1135679>&nbsp;</td>
  <td class=xl1295679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1275679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1285679>&nbsp;</td>
  <td class=xl1145679>&nbsp;</td>
  <td class=xl1145679>&nbsp;</td>
  <td class=xl1155679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=9 style="mso-height-source:userset;height:6.75pt">
  <td height=9 class=xl725679 style="height:6.75pt"></td>
  <td class=xl765679>&nbsp;</td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl775679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=19 style="mso-height-source:userset;height:14.25pt">
  <td height=19 class=xl725679 style="height:14.25pt"></td>
  <td colspan=32 class=xl1935679 style="border-right:1.0pt solid black">&quot;
  Terima kasih Telah Membayar Pajak - Pajak Untuk Pembangunan Bangsa &quot;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=20 style="height:15.0pt">
  <td height=20 class=xl725679 style="height:15.0pt"></td>
  <td colspan=32 class=xl685679 style="border-right:1.0pt solid black">Ruang
  Validasi Kantor Penerima Pembayaran</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td class=xl965679>&nbsp;</td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl975679></td>
  <td class=xl985679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td colspan=32 class=xl655679 style="border-right:1.0pt solid black">&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td class=xl655679>&nbsp;</td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl665679></td>
  <td class=xl675679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td colspan=32 class=xl655679 style="border-right:1.0pt solid black">&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td colspan=32 class=xl655679 style="border-right:1.0pt solid black">&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=17 style="height:12.75pt">
  <td height=17 class=xl725679 style="height:12.75pt"></td>
  <td colspan=32 class=xl655679 style="border-right:1.0pt solid black">&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=18 style="height:13.5pt">
  <td height=18 class=xl725679 style="height:13.5pt"></td>
  <td class=xl795679 colspan=3>F.2.0.32.01</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl875679>&nbsp;</td>
  <td class=xl805679>&nbsp;</td>
  <td class=xl725679></td>
 </tr>
 <tr height=7 style="mso-height-source:userset;height:5.25pt">
  <td height=7 class=xl725679 style="height:5.25pt"></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
  <td class=xl725679></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style="display:none">
  <td width=23 style="width:17pt"></td>
  <td width=19 style="width:14pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=24 style="width:18pt"></td>
  <td width=19 style="width:14pt"></td>
  <td width=23 style="width:17pt"></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>

';
$pdf->endPage();

// output the HTML content
$pdf->writeHTML($html2, true, 0, true, 0);

$pdf->Output('My-File-Name.pdf', 'I');
?>